framework:
    asset_mapper:
        # I percorsi da rendere disponibili all'asset mapper.
        paths:
            - assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
