framework:
    cache:
        # Nome univoco della tua app: usato per calcolare namespace stabili per le chiavi cache.
        #prefix_seed: your_vendor_name/app_name

        # La cache "app" salva su filesystem di default.
        # I dati in questa cache dovrebbero persistere tra i deploy.
        # Altre opzioni includono:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (sconsigliato con carichi di scrittura casuale intensi: la frammentazione pu√≤ causare problemi di prestazioni)
        #app: cache.adapter.apcu

        # I pool con namespace usano il backend "app" sopra indicato di default
        #pools:
            #my.dedicated.cache: null
