# Abilita la protezione CSRF stateless per form e login/logout
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - logout
