when@dev:
    debug:
        # Inoltra cloni dei dati di VarDumper a un server centralizzato per ispezionare i dump via CLI o browser.
        # Vedi il comando "server:dump" per avviare un nuovo server.
        dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
