doctrine_migrations:
    migrations_paths:
        # Il namespace è arbitrario ma dovrebbe essere diverso da App\Migrations
        # perché le classi delle migrazioni NON devono essere autoloadate
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
