knp_snappy:
    pdf:
        enabled: true
        binary: '/usr/bin/wkhtmltopdf'
        options:
            enable-local-file-access: true
            javascript-delay: 0
            load-error-handling: ignore
            load-media-error-handling: ignore
    image:
        enabled: false
