framework:
    router:
        # Configura come generare URL in contesti non-HTTP, come comandi CLI.
        # Vedi https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
