security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER]

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_home

            two_factor:
                auth_form_path: 2fa_login # Il nome della route che hai usato in routes.yaml
                check_path: 2fa_login_check # Il nome della route che hai usato in routes.yaml

            custom_authenticator: App\Security\GoogleAuthenticator

            # attiva diversi modi per autenticarsi
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Modo semplice per controllare l'accesso a grandi sezioni del tuo sito
    # Nota: Solo il *primo* controllo accessi corrispondente verrà usato
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: PUBLIC_ACCESS }
        - { path: ^/_components, roles: PUBLIC_ACCESS } # endpoint che Symfony/Twig UX usa per i componenti
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/crew, roles: ROLE_USER }
        - { path: ^/asset, roles: ROLE_USER }
        - { path: ^/mortgage, roles: ROLE_USER }
        - { path: ^/annual-budget, roles: ROLE_USER }
        - { path: ^/company, roles: ROLE_USER }
        - { path: ^/cost, roles: ROLE_USER }
        - { path: ^/income, roles: ROLE_USER }
        - { path: ^/campaign, roles: ROLE_USER }
        - { path: ^/route, roles: ROLE_USER }
        - { path: ^/salary, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Di default, gli hasher delle password sono intensivi in risorse e richiedono tempo. Questo è
            # importante per generare hash di password sicuri. Nei test tuttavia, gli hash sicuri
            # non sono importanti, sprecano risorse e aumentano i tempi di test. Il seguente
            # riduce il fattore di lavoro ai valori più bassi possibili.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valore più basso possibile per bcrypt
                time_cost: 3 # Valore più basso possibile per argon
                memory_cost: 10 # Valore più basso possibile per argon
