symfonycasts_tailwind:
    # Specifica la versione ESATTA di Tailwind CSS che vuoi usare
    binary_version: 'v4.1.11'

    # In alternativa, puoi specificare il percorso del binario che gestisci tu
    #binary: 'node_modules/.bin/tailwindcss'
