framework:
    validation:
        # Abilita il supporto di auto-mapping del validator.
        # Per esempio, i vincoli di validazione base verranno inferiti dai metadati di Doctrine.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
